# The node ID, peer ID/address map (empty for single node), and log level.
id: 1
peers: {}
log_level: INFO

# Network addresses to bind the SQL and Raft servers to.
listen_sql: 0.0.0.0:9605
listen_raft: 0.0.0.0:9705

# Node data directory, and the garbage ratio threshold at which to trigger
# database compaction when opening the database (Bitcask only).
data_dir: data
compact_threshold: 0.2

# Whether to fsync writes. Fsyncing guarantees that committed data is persisted
# to disk, but has a high performance penalty. Disabling fsync and relying on
# cluster redundancy for data durability may be a reasonable trade-off, although
# this can compromise Raft linearizability guarantees in rare edge cases where
# committed entries lose majority.
sync: true

# Raft log storage engine
# - bitcask (default): an append-only log-structured store.
# - memory: an in-memory store using the Rust standard library's BTreeMap.
storage_raft: bitcask

# SQL key-value storage engine
# - bitcask (default): an append-only log-structured store.
# - memory: an in-memory store using the Rust standard library's BTreeMap.
storage_sql: bitcask
